### PR TITLE
Correct the sds data structure

### LINKED ISSUE #898: Our JSON definition of load balancing weight is incorrect
I don't believe load balancing weights are implemented in Istio, but the data structure in _discovery.go_ does not match Envoy.

Istio will serialize the weight as a peer to the IP address (following https://github.com/istio/pilot/blob/master/proxy/envoy/discovery.go#L156 ) but the Envoy documentation says the weight goes under _tags_.

https://lyft.github.io/envoy/docs/configuration/cluster_manager/sds_api.html#config-cluster-manager-sds-api

### PR DESCRIPTION
**Pull request by liamawhite**
Resolves #898

### CODE REVIEW

File: proxy/envoy/discovery.go [hunk 1]
```diff
@@ -151,6 +151,12 @@ type hosts struct {
 type host struct {
 	Address string `json:"ip_address"`
 	Port    int    `json:"port"`
+	Tags    tags   `json:"tags,omitempty"`
```
Comment (esnible) [inline proxy/envoy/discovery.go]: Perhaps we want *tags instead of tags?  I played around with this last week (trying to write my own, non-Istio SDS) and the _omitempty_ didn't do what I wanted unless tags was a *.

Comment (liamawhite) [inline proxy/envoy/discovery.go]: I don't think pointers should effect the behaviour of omitempty?

Comment (esnible) [inline proxy/envoy/discovery.go]: I wrote this: ```type tags struct {
	Weight int `json:"load_balancing_weight,omitempty"`
}

type host1 struct {
	Address string `json:"ip_address"`
	Port    int    `json:"port"`
	Tags    *tags  `json:"tags,omitempty"`
}

type host2 struct {
	Address string `json:"ip_address"`
	Port    int    `json:"port"`
	Tags    tags  `json:"tags,omitempty"`
}

func main() {
	var h1 host1
	var h2 host2
	
	sh1, _ := json.Marshal(h1)
	sh2, _ := json.Marshal(h2)
	
	fmt.Printf("h1 marshals as %v\n", string(sh1)) 
	fmt.Printf("h2 marshals as %v\n", string(sh2)) 
}``` The output was ```h1 marshals as {"ip_address":"","port":0}
h2 marshals as {"ip_address":"","port":0,"tags":{}}```

Comment (liamawhite) [inline proxy/envoy/discovery.go]: I see now. Thats because an empty pointer is nil but an empty tag is tag{}.

Probably makes sense to go with the pointer.

**Comment by rshriram** [comment]
Ping?
