### PR TITLE
Fix for missing CRD error message

### LINKED ISSUE #1226: pilot failed to start due to `failed to register custom resources.`
I was deploying istio from source code of https://github.com/istio/istio/blob/master/install/kubernetes/istio.yaml

After pilot is deployed, it keeps failing due to following:

```
I0910 06:04:12.888505       1 main.go:90] mesh configuration (*istio_proxy_v1_config.ProxyMeshConfig)(0xc420476200)(egress_proxy_address:"istio-egress:80" discovery_address:"istio-pilot:8080" mixer_address:"istio-mixer:9091" zipkin_address:"zipkin:9411" statsd_udp_address:"istio-mixer:9125" proxy_listen_port:15001 proxy_admin_port:15000 drain_duration:<seconds:2 > parent_shutdown_duration:<seconds:3 > istio_service_cluster:"istio-proxy" discovery_refresh_delay:<seconds:1 > connect_timeout:<seconds:1 > ingress_class:"istio" ingress_service:"istio-ingress" ingress_controller_mode:STRICT auth_policy:MUTUAL_TLS auth_certs_path:"/etc/certs" )
I0910 06:04:12.888553       1 main.go:91] version bootstrap@4f4fcc17-94d0-11e7-961f-0a580a2c491d-330dd286541d1b84c5ac1f4fc504556796c070af-330dd286541d1b84c5ac1f4fc504556796c070af
I0910 06:04:12.892865       1 main.go:92] flags (main.args) {
 kubeconfig: (string) "",
 meshconfig: (string) (len=22) "/etc/istio/config/mesh",
 controllerOptions: (kube.ControllerOptions) {
  Namespace: (string) "",
  WatchedNamespace: (string) "",
  ResyncPeriod: (time.Duration) 1m0s,
  DomainSuffix: (string) (len=13) "cluster.local"
 },
 discoveryOptions: (envoy.DiscoveryServiceOptions) {
  Port: (int) 8080,
  EnableProfiling: (bool) true,
  EnableCaching: (bool) true
 },
 registries: ([]string) (len=1 cap=1) {
  (string) (len=10) "Kubernetes"
 },
 consul: (main.consulArgs) {
  config: (string) "",
  serverURL: (string) ""
 },
 eureka: (main.eurekaArgs) {
  serverURL: (string) ""
 },
 admissionArgs: (admit.ControllerOptions) {
  Descriptor: (model.ConfigDescriptor) <nil>,
  ExternalAdmissionWebhookName: (string) (len=22) "pilot-webhook.istio.io",
  ServiceName: (string) (len=20) "istio-pilot-external",
  ServiceNamespace: (string) "",
  ValidateNamespaces: ([]string) <nil>,
  DomainSuffix: (string) "",
  SecretName: (string) (len=13) "pilot-webhook",
  Port: (int) 443,
  RegistrationDelay: (time.Duration) 5s
 }
}
W0910 06:04:12.892899       1 client_config.go:529] Neither --kubeconfig nor --master was specified.  Using the inClusterConfig.  This might not work.
I0910 06:04:12.895114       1 client.go:167] registering CRD "routerules.config.istio.io"
I0910 06:04:12.905729       1 client.go:167] registering CRD "egressrules.config.istio.io"
I0910 06:04:12.918125       1 client.go:167] registering CRD "destinationpolicies.config.istio.io"
W0910 06:04:13.426871       1 client.go:192] name conflict: ListKindConflict
I0910 06:04:13.426889       1 client.go:196] missing status condition for "routerules.config.istio.io"
W0910 06:04:13.927286       1 client.go:192] name conflict: ListKindConflict
I0910 06:04:13.927303       1 client.go:196] missing status condition for "routerules.config.istio.io"
W0910 06:04:14.426460       1 client.go:192] name conflict: ListKindConflict
I0910 06:04:14.426478       1 client.go:196] missing status condition for "routerules.config.istio.io"
W0910 06:04:14.926396       1 client.go:192] name conflict: ListKindConflict
I0910 06:04:14.926415       1 client.go:196] missing status condition for "routerules.config.istio.io"
W0910 06:04:15.426633       1 client.go:192] name conflict: ListKindConflict
I0910 06:04:15.426653       1 client.go:196] missing status condition for "routerules.config.istio.io"
W0910 06:04:15.927013       1 client.go:192] name conflict: ListKindConflict
I0910 06:04:15.927044       1 client.go:196] missing status condition for "routerules.config.istio.io"
W0910 06:04:16.427463       1 client.go:192] name conflict: ListKindConflict
I0910 06:04:16.427482       1 client.go:196] missing status condition for "routerules.config.istio.io"
W0910 06:04:16.926595       1 client.go:192] name conflict: ListKindConflict
I0910 06:04:16.926618       1 client.go:196] missing status condition for "routerules.config.istio.io"
W0910 06:04:17.426757       1 client.go:192] name conflict: ListKindConflict
I0910 06:04:17.426776       1 client.go:196] missing status condition for "routerules.config.istio.io"
W0910 06:04:17.927704       1 client.go:192] name conflict: ListKindConflict
I0910 06:04:17.927722       1 client.go:196] missing status condition for "routerules.config.istio.io"
W0910 06:04:18.426652       1 client.go:192] name conflict: ListKindConflict
I0910 06:04:18.426671       1 client.go:196] missing status condition for "routerules.config.istio.io"
W0910 06:04:18.926185       1 client.go:192] name conflict: ListKindConflict
I0910 06:04:18.926207       1 client.go:196] missing status condition for "routerules.config.istio.io"
W0910 06:04:19.426734       1 client.go:192] name conflict: ListKindConflict
I0910 06:04:19.426752       1 client.go:196] missing status condition for "routerules.config.istio.io"
W0910 06:04:19.926624       1 client.go:192] name conflict: ListKindConflict
I0910 06:04:19.926642       1 client.go:196] missing status condition for "routerules.config.istio.io"
W0910 06:04:20.426300       1 client.go:192] name conflict: ListKindConflict
I0910 06:04:20.426326       1 client.go:196] missing status condition for "routerules.config.istio.io"
W0910 06:04:20.927228       1 client.go:192] name conflict: ListKindConflict
I0910 06:04:20.927248       1 client.go:196] missing status condition for "routerules.config.istio.io"
W0910 06:04:21.427091       1 client.go:192] name conflict: ListKindConflict
I0910 06:04:21.427110       1 client.go:196] missing status condition for "routerules.config.istio.io"
W0910 06:04:21.926796       1 client.go:192] name conflict: ListKindConflict
I0910 06:04:21.926815       1 client.go:196] missing status condition for "routerules.config.istio.io"
W0910 06:04:22.426575       1 client.go:192] name conflict: ListKindConflict
I0910 06:04:22.426592       1 client.go:196] missing status condition for "routerules.config.istio.io"
W0910 06:04:22.926560       1 client.go:192] name conflict: ListKindConflict
I0910 06:04:22.926634       1 client.go:196] missing status condition for "routerules.config.istio.io"
W0910 06:04:23.426808       1 client.go:192] name conflict: ListKindConflict
I0910 06:04:23.426827       1 client.go:196] missing status condition for "routerules.config.istio.io"
W0910 06:04:23.926964       1 client.go:192] name conflict: ListKindConflict
I0910 06:04:23.926984       1 client.go:196] missing status condition for "routerules.config.istio.io"
W0910 06:04:24.426899       1 client.go:192] name conflict: ListKindConflict
I0910 06:04:24.426920       1 client.go:196] missing status condition for "routerules.config.istio.io"
W0910 06:04:24.926968       1 client.go:192] name conflict: ListKindConflict
I0910 06:04:24.927052       1 client.go:196] missing status condition for "routerules.config.istio.io"
W0910 06:04:25.426817       1 client.go:192] name conflict: ListKindConflict
I0910 06:04:25.426846       1 client.go:196] missing status condition for "routerules.config.istio.io"
W0910 06:04:25.927377       1 client.go:192] name conflict: ListKindConflict
I0910 06:04:25.927398       1 client.go:196] missing status condition for "routerules.config.istio.io"
W0910 06:04:26.427710       1 client.go:192] name conflict: ListKindConflict
I0910 06:04:26.427739       1 client.go:196] missing status condition for "routerules.config.istio.io"
W0910 06:04:26.927092       1 client.go:192] name conflict: ListKindConflict
I0910 06:04:26.927113       1 client.go:196] missing status condition for "routerules.config.istio.io"
W0910 06:04:27.427278       1 client.go:192] name conflict: ListKindConflict
I0910 06:04:27.427309       1 client.go:196] missing status condition for "routerules.config.istio.io"
W0910 06:04:27.927715       1 client.go:192] name conflict: ListKindConflict
I0910 06:04:27.927850       1 client.go:196] missing status condition for "routerules.config.istio.io"
W0910 06:04:28.428097       1 client.go:192] name conflict: ListKindConflict
I0910 06:04:28.428179       1 client.go:196] missing status condition for "routerules.config.istio.io"
W0910 06:04:28.927485       1 client.go:192] name conflict: ListKindConflict
I0910 06:04:28.927505       1 client.go:196] missing status condition for "routerules.config.istio.io"
W0910 06:04:29.426834       1 client.go:192] name conflict: ListKindConflict
I0910 06:04:29.426852       1 client.go:196] missing status condition for "routerules.config.istio.io"
W0910 06:04:29.926975       1 client.go:192] name conflict: ListKindConflict
I0910 06:04:29.927011       1 client.go:196] missing status condition for "routerules.config.istio.io"
W0910 06:04:30.426800       1 client.go:192] name conflict: ListKindConflict
I0910 06:04:30.426820       1 client.go:196] missing status condition for "routerules.config.istio.io"
W0910 06:04:30.926688       1 client.go:192] name conflict: ListKindConflict
I0910 06:04:30.926709       1 client.go:196] missing status condition for "routerules.config.istio.io"
W0910 06:04:31.426810       1 client.go:192] name conflict: ListKindConflict
I0910 06:04:31.426829       1 client.go:196] missing status condition for "routerules.config.istio.io"
W0910 06:04:31.926703       1 client.go:192] name conflict: ListKindConflict
I0910 06:04:31.926731       1 client.go:196] missing status condition for "routerules.config.istio.io"
W0910 06:04:32.427096       1 client.go:192] name conflict: ListKindConflict
I0910 06:04:32.427130       1 client.go:196] missing status condition for "routerules.config.istio.io"
W0910 06:04:32.927103       1 client.go:192] name conflict: ListKindConflict
I0910 06:04:32.927160       1 client.go:196] missing status condition for "routerules.config.istio.io"
W0910 06:04:33.427261       1 client.go:192] name conflict: ListKindConflict
I0910 06:04:33.427280       1 client.go:196] missing status condition for "routerules.config.istio.io"
W0910 06:04:33.926703       1 client.go:192] name conflict: ListKindConflict
I0910 06:04:33.926735       1 client.go:196] missing status condition for "routerules.config.istio.io"
W0910 06:04:34.426484       1 client.go:192] name conflict: ListKindConflict
I0910 06:04:34.426504       1 client.go:196] missing status condition for "routerules.config.istio.io"
W0910 06:04:34.926648       1 client.go:192] name conflict: ListKindConflict
I0910 06:04:34.926670       1 client.go:196] missing status condition for "routerules.config.istio.io"
W0910 06:04:35.426667       1 client.go:192] name conflict: ListKindConflict
I0910 06:04:35.426686       1 client.go:196] missing status condition for "routerules.config.istio.io"
W0910 06:04:35.927134       1 client.go:192] name conflict: ListKindConflict
I0910 06:04:35.927154       1 client.go:196] missing status condition for "routerules.config.istio.io"
W0910 06:04:36.427841       1 client.go:192] name conflict: ListKindConflict
I0910 06:04:36.427875       1 client.go:196] missing status condition for "routerules.config.istio.io"
W0910 06:04:36.928530       1 client.go:192] name conflict: ListKindConflict
I0910 06:04:36.928572       1 client.go:196] missing status condition for "routerules.config.istio.io"
W0910 06:04:37.426751       1 client.go:192] name conflict: ListKindConflict
I0910 06:04:37.426771       1 client.go:196] missing status condition for "routerules.config.istio.io"
W0910 06:04:37.926564       1 client.go:192] name conflict: ListKindConflict
I0910 06:04:37.926588       1 client.go:196] missing status condition for "routerules.config.istio.io"
W0910 06:04:38.426846       1 client.go:192] name conflict: ListKindConflict
I0910 06:04:38.426870       1 client.go:196] missing status condition for "routerules.config.istio.io"
W0910 06:04:38.926158       1 client.go:192] name conflict: ListKindConflict
I0910 06:04:38.926180       1 client.go:196] missing status condition for "routerules.config.istio.io"
W0910 06:04:39.426525       1 client.go:192] name conflict: ListKindConflict
I0910 06:04:39.426545       1 client.go:196] missing status condition for "routerules.config.istio.io"
W0910 06:04:39.926982       1 client.go:192] name conflict: ListKindConflict
I0910 06:04:39.927069       1 client.go:196] missing status condition for "routerules.config.istio.io"
W0910 06:04:40.426469       1 client.go:192] name conflict: ListKindConflict
I0910 06:04:40.426501       1 client.go:196] missing status condition for "routerules.config.istio.io"
W0910 06:04:40.926584       1 client.go:192] name conflict: ListKindConflict
I0910 06:04:40.926602       1 client.go:196] missing status condition for "routerules.config.istio.io"
W0910 06:04:41.426755       1 client.go:192] name conflict: ListKindConflict
I0910 06:04:41.426788       1 client.go:196] missing status condition for "routerules.config.istio.io"
W0910 06:04:41.926716       1 client.go:192] name conflict: ListKindConflict
I0910 06:04:41.926733       1 client.go:196] missing status condition for "routerules.config.istio.io"
W0910 06:04:42.426764       1 client.go:192] name conflict: ListKindConflict
I0910 06:04:42.426782       1 client.go:196] missing status condition for "routerules.config.istio.io"
W0910 06:04:42.927172       1 client.go:192] name conflict: ListKindConflict
I0910 06:04:42.927190       1 client.go:196] missing status condition for "routerules.config.istio.io"
W0910 06:04:43.426631       1 client.go:192] name conflict: ListKindConflict
I0910 06:04:43.426652       1 client.go:196] missing status condition for "routerules.config.istio.io"
W0910 06:04:43.929516       1 client.go:192] name conflict: ListKindConflict
I0910 06:04:43.929545       1 client.go:196] missing status condition for "routerules.config.istio.io"
W0910 06:04:44.427139       1 client.go:192] name conflict: ListKindConflict
I0910 06:04:44.427175       1 client.go:196] missing status condition for "routerules.config.istio.io"
W0910 06:04:44.926660       1 client.go:192] name conflict: ListKindConflict
I0910 06:04:44.926681       1 client.go:196] missing status condition for "routerules.config.istio.io"
W0910 06:04:45.427374       1 client.go:192] name conflict: ListKindConflict
I0910 06:04:45.427403       1 client.go:196] missing status condition for "routerules.config.istio.io"
W0910 06:04:45.926950       1 client.go:192] name conflict: ListKindConflict
I0910 06:04:45.926970       1 client.go:196] missing status condition for "routerules.config.istio.io"
W0910 06:04:46.427146       1 client.go:192] name conflict: ListKindConflict
I0910 06:04:46.427168       1 client.go:196] missing status condition for "routerules.config.istio.io"
W0910 06:04:46.926216       1 client.go:192] name conflict: ListKindConflict
I0910 06:04:46.926244       1 client.go:196] missing status condition for "routerules.config.istio.io"
W0910 06:04:47.427262       1 client.go:192] name conflict: ListKindConflict
I0910 06:04:47.427283       1 client.go:196] missing status condition for "routerules.config.istio.io"
W0910 06:04:47.926452       1 client.go:192] name conflict: ListKindConflict
I0910 06:04:47.926473       1 client.go:196] missing status condition for "routerules.config.istio.io"
W0910 06:04:48.426844       1 client.go:192] name conflict: ListKindConflict
I0910 06:04:48.426861       1 client.go:196] missing status condition for "routerules.config.istio.io"
W0910 06:04:48.926273       1 client.go:192] name conflict: ListKindConflict
I0910 06:04:48.926291       1 client.go:196] missing status condition for "routerules.config.istio.io"
W0910 06:04:49.434546       1 client.go:192] name conflict: ListKindConflict
I0910 06:04:49.434564       1 client.go:196] missing status condition for "routerules.config.istio.io"
W0910 06:04:49.926784       1 client.go:192] name conflict: ListKindConflict
I0910 06:04:49.926809       1 client.go:196] missing status condition for "routerules.config.istio.io"
W0910 06:04:50.426138       1 client.go:192] name conflict: ListKindConflict
I0910 06:04:50.426157       1 client.go:196] missing status condition for "routerules.config.istio.io"
W0910 06:04:50.926833       1 client.go:192] name conflict: ListKindConflict
I0910 06:04:50.926870       1 client.go:196] missing status condition for "routerules.config.istio.io"
W0910 06:04:51.426617       1 client.go:192] name conflict: ListKindConflict
I0910 06:04:51.426635       1 client.go:196] missing status condition for "routerules.config.istio.io"
W0910 06:04:51.926828       1 client.go:192] name conflict: ListKindConflict
I0910 06:04:51.926886       1 client.go:196] missing status condition for "routerules.config.istio.io"
W0910 06:04:52.427556       1 client.go:192] name conflict: ListKindConflict
I0910 06:04:52.427575       1 client.go:196] missing status condition for "routerules.config.istio.io"
W0910 06:04:52.926605       1 client.go:192] name conflict: ListKindConflict
I0910 06:04:52.926627       1 client.go:196] missing status condition for "routerules.config.istio.io"
W0910 06:04:53.435155       1 client.go:192] name conflict: ListKindConflict
I0910 06:04:53.435173       1 client.go:196] missing status condition for "routerules.config.istio.io"
W0910 06:04:53.926687       1 client.go:192] name conflict: ListKindConflict
I0910 06:04:53.926705       1 client.go:196] missing status condition for "routerules.config.istio.io"
W0910 06:04:54.426910       1 client.go:192] name conflict: ListKindConflict
I0910 06:04:54.426929       1 client.go:196] missing status condition for "routerules.config.istio.io"
W0910 06:04:54.927019       1 client.go:192] name conflict: ListKindConflict
I0910 06:04:54.927157       1 client.go:196] missing status condition for "routerules.config.istio.io"
W0910 06:04:55.426828       1 client.go:192] name conflict: ListKindConflict
I0910 06:04:55.426847       1 client.go:196] missing status condition for "routerules.config.istio.io"
W0910 06:04:55.926451       1 client.go:192] name conflict: ListKindConflict
I0910 06:04:55.926469       1 client.go:196] missing status condition for "routerules.config.istio.io"
W0910 06:04:56.426616       1 client.go:192] name conflict: ListKindConflict
I0910 06:04:56.426634       1 client.go:196] missing status condition for "routerules.config.istio.io"
W0910 06:04:56.926496       1 client.go:192] name conflict: ListKindConflict
I0910 06:04:56.926514       1 client.go:196] missing status condition for "routerules.config.istio.io"
W0910 06:04:57.426780       1 client.go:192] name conflict: ListKindConflict
I0910 06:04:57.426801       1 client.go:196] missing status condition for "routerules.config.istio.io"
W0910 06:04:57.926898       1 client.go:192] name conflict: ListKindConflict
I0910 06:04:57.926921       1 client.go:196] missing status condition for "routerules.config.istio.io"
W0910 06:04:58.426596       1 client.go:192] name conflict: ListKindConflict
I0910 06:04:58.426615       1 client.go:196] missing status condition for "routerules.config.istio.io"
W0910 06:04:58.926372       1 client.go:192] name conflict: ListKindConflict
I0910 06:04:58.926391       1 client.go:196] missing status condition for "routerules.config.istio.io"
W0910 06:04:59.426647       1 client.go:192] name conflict: ListKindConflict
I0910 06:04:59.426692       1 client.go:196] missing status condition for "routerules.config.istio.io"
W0910 06:04:59.926442       1 client.go:192] name conflict: ListKindConflict
I0910 06:04:59.926462       1 client.go:196] missing status condition for "routerules.config.istio.io"
W0910 06:05:00.426711       1 client.go:192] name conflict: ListKindConflict
I0910 06:05:00.426732       1 client.go:196] missing status condition for "routerules.config.istio.io"
W0910 06:05:00.928802       1 client.go:192] name conflict: ListKindConflict
I0910 06:05:00.928835       1 client.go:196] missing status condition for "routerules.config.istio.io"
W0910 06:05:01.427427       1 client.go:192] name conflict: ListKindConflict
I0910 06:05:01.427447       1 client.go:196] missing status condition for "routerules.config.istio.io"
W0910 06:05:01.926314       1 client.go:192] name conflict: ListKindConflict
I0910 06:05:01.926405       1 client.go:196] missing status condition for "routerules.config.istio.io"
W0910 06:05:02.426731       1 client.go:192] name conflict: ListKindConflict
I0910 06:05:02.426814       1 client.go:196] missing status condition for "routerules.config.istio.io"
W0910 06:05:02.926991       1 client.go:192] name conflict: ListKindConflict
I0910 06:05:02.927024       1 client.go:196] missing status condition for "routerules.config.istio.io"
W0910 06:05:03.426895       1 client.go:192] name conflict: ListKindConflict
I0910 06:05:03.426928       1 client.go:196] missing status condition for "routerules.config.istio.io"
W0910 06:05:03.926862       1 client.go:192] name conflict: ListKindConflict
I0910 06:05:03.926996       1 client.go:196] missing status condition for "routerules.config.istio.io"
W0910 06:05:04.426933       1 client.go:192] name conflict: ListKindConflict
I0910 06:05:04.426964       1 client.go:196] missing status condition for "routerules.config.istio.io"
W0910 06:05:04.926527       1 client.go:192] name conflict: ListKindConflict
I0910 06:05:04.926546       1 client.go:196] missing status condition for "routerules.config.istio.io"
W0910 06:05:05.427287       1 client.go:192] name conflict: ListKindConflict
I0910 06:05:05.427338       1 client.go:196] missing status condition for "routerules.config.istio.io"
W0910 06:05:05.926939       1 client.go:192] name conflict: ListKindConflict
I0910 06:05:05.926956       1 client.go:196] missing status condition for "routerules.config.istio.io"
W0910 06:05:06.427419       1 client.go:192] name conflict: ListKindConflict
I0910 06:05:06.427450       1 client.go:196] missing status condition for "routerules.config.istio.io"
W0910 06:05:06.926756       1 client.go:192] name conflict: ListKindConflict
I0910 06:05:06.926792       1 client.go:196] missing status condition for "routerules.config.istio.io"
W0910 06:05:07.427019       1 client.go:192] name conflict: ListKindConflict
I0910 06:05:07.427040       1 client.go:196] missing status condition for "routerules.config.istio.io"
W0910 06:05:07.953021       1 client.go:192] name conflict: ListKindConflict
I0910 06:05:07.953042       1 client.go:196] missing status condition for "routerules.config.istio.io"
W0910 06:05:08.426760       1 client.go:192] name conflict: ListKindConflict
I0910 06:05:08.426778       1 client.go:196] missing status condition for "routerules.config.istio.io"
W0910 06:05:08.927276       1 client.go:192] name conflict: ListKindConflict
I0910 06:05:08.927307       1 client.go:196] missing status condition for "routerules.config.istio.io"
W0910 06:05:09.426979       1 client.go:192] name conflict: ListKindConflict
I0910 06:05:09.426999       1 client.go:196] missing status condition for "routerules.config.istio.io"
W0910 06:05:09.932653       1 client.go:192] name conflict: ListKindConflict
I0910 06:05:09.932731       1 client.go:196] missing status condition for "routerules.config.istio.io"
W0910 06:05:10.426797       1 client.go:192] name conflict: ListKindConflict
I0910 06:05:10.426825       1 client.go:196] missing status condition for "routerules.config.istio.io"
W0910 06:05:10.926677       1 client.go:192] name conflict: ListKindConflict
I0910 06:05:10.926755       1 client.go:196] missing status condition for "routerules.config.istio.io"
W0910 06:05:11.427221       1 client.go:192] name conflict: ListKindConflict
I0910 06:05:11.427239       1 client.go:196] missing status condition for "routerules.config.istio.io"
W0910 06:05:11.926640       1 client.go:192] name conflict: ListKindConflict
I0910 06:05:11.926664       1 client.go:196] missing status condition for "routerules.config.istio.io"
W0910 06:05:12.427016       1 client.go:192] name conflict: ListKindConflict
I0910 06:05:12.427048       1 client.go:196] missing status condition for "routerules.config.istio.io"
W0910 06:05:12.926588       1 client.go:192] name conflict: ListKindConflict
I0910 06:05:12.926607       1 client.go:196] missing status condition for "routerules.config.istio.io"
W0910 06:05:12.929123       1 client.go:192] name conflict: ListKindConflict
I0910 06:05:12.929138       1 client.go:196] missing status condition for "routerules.config.istio.io"
Error: 3 errors occurred:

* failed to register custom resources. <nil>
* failed to register custom resources. <nil>
* failed to register custom resources. <nil>
Usage:
  pilot discovery [flags]

Flags:
      --admission-registration-delay duration   Time to delay webhook registration after starting webhook server (default 5s)
      --admission-secret string                 Name of k8s secret for pilot webhook certs (default "pilot-webhook")
      --admission-service string                Service name the admission controller uses during registration (default "istio-pilot-external")
      --admission-service-port int              HTTPS port of the admission service. Must be 443 if service has more than one port  (default 443)
      --admission-webhook-name string           Webhook name for Pilot admission controller (default "pilot-webhook.istio.io")
  -a, --app namespace string                    Restrict the applications namespace the controller manages; if not set, controller watches all namespaces
      --consulconfig string                     Consul Config file for discovery
      --consulserverURL string                  URL for the Consul server
      --discovery_cache                         Enable caching discovery service responses (default true)
      --domain string                           DNS domain suffix (default "cluster.local")
      --eurekaserverURL string                  URL for the Eureka server
  -h, --help                                    help for discovery
      --kubeconfig string                       Use a Kubernetes configuration file instead of in-cluster configuration
      --meshConfig string                       File name for Istio mesh configuration (default "/etc/istio/config/mesh")
  -n, --namespace string                        Select a namespace for the controller loop. If not set, uses ${POD_NAMESPACE} environment variable
      --port int                                Discovery service port (default 8080)
      --profile                                 Enable profiling via web interface host:port/debug/pprof (default true)
      --registries stringSlice                  Comma separated list of platform service registries to read from (choose one or more from {Kubernetes, Consul, Eureka}) (default [Kubernetes])
      --resync duration                         Controller resync interval (default 1m0s)

Global Flags:
      --log_backtrace_at traceLocation   when logging hits line file:N, emit a stack trace (default :0)
  -v, --v Level                          log level for V logs (default 0)
      --vmodule moduleSpec               comma-separated list of pattern=N settings for file-filtered logging

E0910 06:05:12.948754       1 main.go:279] 3 errors occurred:

* failed to register custom resources. <nil>
* failed to register custom resources. <nil>
* failed to register custom resources. <nil>
```

After I assign `cluster-admin` role to `default:istio-pilot-service-account`, still failed.

```
 kubectl create clusterrolebinding cluster-admin-pilot --clusterrole=cluster-admin --serviceaccount=default:istio-pilot-service-account
```

Can someone help check what is wrong? Thanks.

### PR DESCRIPTION
**Pull request by kyessenov**
**What this PR does / why we need it**:

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #1226

**Special notes for your reviewer**:

**Release note**:

```release-note
```

### CODE REVIEW

File: adapter/config/crd/client.go [hunk 1]
```diff
@@ -194,17 +194,17 @@ func (cl *Client) RegisterResources() error {
 				}
 			}
 			glog.V(2).Infof("missing status condition for %q", name)
-			return false, err
+			return false, nil
 		}
```
Comment (ldemailly) [inline adapter/config/crd/client.go]: On a phone so hard to see the big picture but why would returning less info (nil vs err) be better ?

Comment (kyessenov) [reply adapter/config/crd/client.go]: `err` is nil here always since it's a wrong variable.
